package com.ehr.model;

import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Activity {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.theme
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String theme;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.activityAddress
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String activityaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.introduce
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String introduce;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.activityTheDetail
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String activitythedetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.initateTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
    private Date initatetime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.spending
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer spending;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.state
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_activity.logicToDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.id
     *
     * @return the value of ehr_activity.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.id
     *
     * @param id the value for ehr_activity.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.theme
     *
     * @return the value of ehr_activity.theme
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getTheme() {
        return theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.theme
     *
     * @param theme the value for ehr_activity.theme
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setTheme(String theme) {
        this.theme = theme;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.activityAddress
     *
     * @return the value of ehr_activity.activityAddress
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getActivityaddress() {
        return activityaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.activityAddress
     *
     * @param activityaddress the value for ehr_activity.activityAddress
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setActivityaddress(String activityaddress) {
        this.activityaddress = activityaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.introduce
     *
     * @return the value of ehr_activity.introduce
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getIntroduce() {
        return introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.introduce
     *
     * @param introduce the value for ehr_activity.introduce
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setIntroduce(String introduce) {
        this.introduce = introduce;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.activityTheDetail
     *
     * @return the value of ehr_activity.activityTheDetail
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getActivitythedetail() {
        return activitythedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.activityTheDetail
     *
     * @param activitythedetail the value for ehr_activity.activityTheDetail
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setActivitythedetail(String activitythedetail) {
        this.activitythedetail = activitythedetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.initateTime
     *
     * @return the value of ehr_activity.initateTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Date getInitatetime() {
        return initatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.initateTime
     *
     * @param initatetime the value for ehr_activity.initateTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setInitatetime(Date initatetime) {
        this.initatetime = initatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.spending
     *
     * @return the value of ehr_activity.spending
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getSpending() {
        return spending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.spending
     *
     * @param spending the value for ehr_activity.spending
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setSpending(Integer spending) {
        this.spending = spending;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.state
     *
     * @return the value of ehr_activity.state
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.state
     *
     * @param state the value for ehr_activity.state
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.emp_id
     *
     * @return the value of ehr_activity.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.emp_id
     *
     * @param empId the value for ehr_activity.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_activity.logicToDelete
     *
     * @return the value of ehr_activity.logicToDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_activity.logicToDelete
     *
     * @param logictodelete the value for ehr_activity.logicToDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

	public Activity() {
		super();
		// TODO Auto-generated constructor stub
	}

	public Activity(Integer id, String theme, String activityaddress, String introduce, String activitythedetail,
			Date initatetime, Integer spending, Integer state, Integer empId, Integer logictodelete) {
		super();
		this.id = id;
		this.theme = theme;
		this.activityaddress = activityaddress;
		this.introduce = introduce;
		this.activitythedetail = activitythedetail;
		this.initatetime = initatetime;
		this.spending = spending;
		this.state = state;
		this.empId = empId;
		this.logictodelete = logictodelete;
	}
    
}