package com.ehr.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * 应聘者管理
 * ehr_applicant表对应的POJO类
 * @author WW
 *
 */
public class Applicant {
    private Integer id;//编号
    private String name;//名字
    private Integer sex;//性别
    private String phone;//电话
    private String qq;//QQ
    private String email;//邮箱
    private Integer age;//年龄
    private String currentaddress;//现住址
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date applicanttime;//应聘时间
    private String specialty;//技术特长
    private String comments;//面试官评价
    private String mark;//备注
    private Integer logictodelete;//逻辑删除字段
    
    //性别为数字 存储转化为字符串的性别
    private String sexStr;
    

    public String getSexStr() {
		return sexStr;
	}

	public void setSexStr(String sexStr) {
		this.sexStr = sexStr;
	}

	@Override
	public String toString() {
		return "Applicant [id=" + id + ", name=" + name + ", sex=" + sex + ", phone=" + phone + ", qq=" + qq
				+ ", email=" + email + ", age=" + age + ", currentaddress=" + currentaddress + ", applicanttime="
				+ applicanttime + ", specialty=" + specialty + ", comments=" + comments + ", mark=" + mark
				+ ", logictodelete=" + logictodelete + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.id
     *
     * @return the value of ehr_applicant.id
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.id
     *
     * @param id the value for ehr_applicant.id
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.name
     *
     * @return the value of ehr_applicant.name
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.name
     *
     * @param name the value for ehr_applicant.name
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.sex
     *
     * @return the value of ehr_applicant.sex
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.sex
     *
     * @param sex the value for ehr_applicant.sex
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setSex(Integer sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.phone
     *
     * @return the value of ehr_applicant.phone
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.phone
     *
     * @param phone the value for ehr_applicant.phone
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.qq
     *
     * @return the value of ehr_applicant.qq
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.qq
     *
     * @param qq the value for ehr_applicant.qq
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.email
     *
     * @return the value of ehr_applicant.email
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.email
     *
     * @param email the value for ehr_applicant.email
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.age
     *
     * @return the value of ehr_applicant.age
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.age
     *
     * @param age the value for ehr_applicant.age
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.currentAddress
     *
     * @return the value of ehr_applicant.currentAddress
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.currentAddress
     *
     * @param currentaddress the value for ehr_applicant.currentAddress
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.applicantTime
     *
     * @return the value of ehr_applicant.applicantTime
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Date getApplicanttime() {
        return applicanttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.applicantTime
     *
     * @param applicanttime the value for ehr_applicant.applicantTime
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setApplicanttime(Date applicanttime) {
        this.applicanttime = applicanttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.specialty
     *
     * @return the value of ehr_applicant.specialty
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.specialty
     *
     * @param specialty the value for ehr_applicant.specialty
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.comments
     *
     * @return the value of ehr_applicant.comments
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getComments() {
        return comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.comments
     *
     * @param comments the value for ehr_applicant.comments
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setComments(String comments) {
        this.comments = comments;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.mark
     *
     * @return the value of ehr_applicant.mark
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.mark
     *
     * @param mark the value for ehr_applicant.mark
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_applicant.logicToDelete
     *
     * @return the value of ehr_applicant.logicToDelete
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_applicant.logicToDelete
     *
     * @param logictodelete the value for ehr_applicant.logicToDelete
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}