package com.ehr.model;

import java.util.Date;

import org.springframework.format.annotation.DateTimeFormat;

import com.fasterxml.jackson.annotation.JsonFormat;

public class Attendance {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.clockInTime
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    @JsonFormat(pattern="yyyy-MM-dd HH:mm:ss")
//    @DateTimeFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date clockintime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.clockInIocation
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    private String clockiniocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.tag
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    private Integer tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.emp_id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_attendance.logictoDelete
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.id
     *
     * @return the value of ehr_attendance.id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.id
     *
     * @param id the value for ehr_attendance.id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.clockInTime
     *
     * @return the value of ehr_attendance.clockInTime
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public Date getClockintime() {
        return clockintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.clockInTime
     *
     * @param clockintime the value for ehr_attendance.clockInTime
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setClockintime(Date clockintime) {
        this.clockintime = clockintime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.clockInIocation
     *
     * @return the value of ehr_attendance.clockInIocation
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public String getClockiniocation() {
        return clockiniocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.clockInIocation
     *
     * @param clockiniocation the value for ehr_attendance.clockInIocation
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setClockiniocation(String clockiniocation) {
        this.clockiniocation = clockiniocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.tag
     *
     * @return the value of ehr_attendance.tag
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public Integer getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.tag
     *
     * @param tag the value for ehr_attendance.tag
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setTag(Integer tag) {
        this.tag = tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.emp_id
     *
     * @return the value of ehr_attendance.emp_id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.emp_id
     *
     * @param empId the value for ehr_attendance.emp_id
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_attendance.logictoDelete
     *
     * @return the value of ehr_attendance.logictoDelete
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_attendance.logictoDelete
     *
     * @param logictodelete the value for ehr_attendance.logictoDelete
     *
     * @mbg.generated Sun Jun 23 21:49:02 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

	@Override
	public String toString() {
		return "Attendance [id=" + id + ", clockintime=" + clockintime + ", clockiniocation=" + clockiniocation
				+ ", tag=" + tag + ", empId=" + empId + ", logictodelete=" + logictodelete + ", getId()=" + getId()
				+ ", getClockintime()=" + getClockintime() + ", getClockiniocation()=" + getClockiniocation()
				+ ", getTag()=" + getTag() + ", getEmpId()=" + getEmpId() + ", getLogictodelete()=" + getLogictodelete()
				+ ", getClass()=" + getClass() + ", hashCode()=" + hashCode() + ", toString()=" + super.toString()
				+ "]";
	}
    
}