package com.ehr.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * 渠道管理
 * ehr_channel表对应的POJO类
 * @author WW
 *
 */
public class Channel {
    private Integer id;//编号
    private String name;//渠道名称或地址
    private String mark;//备注
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date addtime;//渠道上传时间
    private Integer logictodelete;//逻辑删除字段
    
    @Override
	public String toString() {
		return "Channel [id=" + id + ", name=" + name + ", mark=" + mark + ", addtime=" + addtime + ", logictodelete="
				+ logictodelete + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_channel.id
     *
     * @return the value of ehr_channel.id
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_channel.id
     *
     * @param id the value for ehr_channel.id
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_channel.name
     *
     * @return the value of ehr_channel.name
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_channel.name
     *
     * @param name the value for ehr_channel.name
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_channel.mark
     *
     * @return the value of ehr_channel.mark
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_channel.mark
     *
     * @param mark the value for ehr_channel.mark
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_channel.addTime
     *
     * @return the value of ehr_channel.addTime
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_channel.addTime
     *
     * @param addtime the value for ehr_channel.addTime
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_channel.logicToDelete
     *
     * @return the value of ehr_channel.logicToDelete
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_channel.logicToDelete
     *
     * @param logictodelete the value for ehr_channel.logicToDelete
     *
     * @mbg.generated Mon Jun 24 10:46:18 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}