package com.ehr.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

public class Company {
    public Company() {
    }

    public Company(Integer id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "Company{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", address='" + address + '\'' +
                ", mark='" + mark + '\'' +
                ", logictodelete=" + logictodelete +
                ", createtime=" + createtime +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.id
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.name
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.address
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.mark
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.logicToDelete
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private Integer logictodelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_company.createTime
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    private Date createtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.id
     *
     * @return the value of ehr_company.id
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.id
     *
     * @param id the value for ehr_company.id
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.name
     *
     * @return the value of ehr_company.name
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.name
     *
     * @param name the value for ehr_company.name
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.address
     *
     * @return the value of ehr_company.address
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.address
     *
     * @param address the value for ehr_company.address
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.mark
     *
     * @return the value of ehr_company.mark
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.mark
     *
     * @param mark the value for ehr_company.mark
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.logicToDelete
     *
     * @return the value of ehr_company.logicToDelete
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.logicToDelete
     *
     * @param logictodelete the value for ehr_company.logicToDelete
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_company.createTime
     *
     * @return the value of ehr_company.createTime
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_company.createTime
     *
     * @param createtime the value for ehr_company.createTime
     *
     * @mbg.generated Sun Jun 23 22:13:42 CST 2019
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }
}