package com.ehr.model;

public class Dept {
    public Dept() {
    }

    public Dept(String name, String mark, Integer companyId, Integer logictodelete, String avatar) {
        this.name = name;
        this.mark = mark;
        this.companyId = companyId;
        this.logictodelete = logictodelete;
        this.avatar = avatar;
    }

    @Override
    public String toString() {
        return "Dept{" +
                "companyName='" + companyName + '\'' +
                ", id=" + id +
                ", name='" + name + '\'' +
                ", mark='" + mark + '\'' +
                ", companyId=" + companyId +
                ", logictodelete=" + logictodelete +
                ", avatar='" + avatar + '\'' +
                '}';
    }

    public Dept(Integer id, String name, String mark, Integer companyId, Integer logictodelete, String avatar) {
        this.id = id;
        this.name = name;
        this.mark = mark;
        this.companyId = companyId;
        this.logictodelete = logictodelete;
        this.avatar = avatar;
    }

    private String companyName;

    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.company_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer logictodelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_dept.avatar
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private String avatar;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.id
     *
     * @return the value of ehr_dept.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.id
     *
     * @param id the value for ehr_dept.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.name
     *
     * @return the value of ehr_dept.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.name
     *
     * @param name the value for ehr_dept.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.mark
     *
     * @return the value of ehr_dept.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.mark
     *
     * @param mark the value for ehr_dept.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.company_id
     *
     * @return the value of ehr_dept.company_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.company_id
     *
     * @param companyId the value for ehr_dept.company_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.logicToDelete
     *
     * @return the value of ehr_dept.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.logicToDelete
     *
     * @param logictodelete the value for ehr_dept.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_dept.avatar
     *
     * @return the value of ehr_dept.avatar
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_dept.avatar
     *
     * @param avatar the value for ehr_dept.avatar
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }
}