package com.ehr.model;

import java.util.Date;

public class Emp {
	
	@Override
	public String toString() {
		return "Emp [deptName=" + deptName + ", posName=" + posName + ", id=" + id + ", userid=" + userid + ", sign="
				+ sign + ", avatar=" + avatar + ", name=" + name + ", password=" + password + ", img=" + img
				+ ", birthday=" + birthday + ", sex=" + sex + ", phone=" + phone + ", qq=" + qq + ", email=" + email
				+ ", age=" + age + ", currentaddress=" + currentaddress + ", inductiontime=" + inductiontime
				+ ", state=" + state + ", specialty=" + specialty + ", mark=" + mark + ", islogin=" + islogin
				+ ", deptId=" + deptId + ", paygradesId=" + paygradesId + ", positionId=" + positionId
				+ ", logictodelete=" + logictodelete + ", status=" + status + "]";
	}

	String deptName;
	String posName;
	
	public String getPosName() {
		return posName;
	}
	public void setPosName(String posName) {
		this.posName=posName;
	}
	
	public String getDeptName() {
		return deptName;
	}
	public void setDeptName(String deptName) {
		this.deptName=deptName;
	}

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.userid
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String userid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.sign
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String sign;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.avatar
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String avatar;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.name
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.password
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.img
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String img;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.birthday
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.sex
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.phone
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.QQ
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.email
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.age
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.currentAddress
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String currentaddress;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.inductionTime
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Date inductiontime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.state
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.specialty
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String specialty;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.mark
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.isLogin
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer islogin;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.dept_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.paygrades_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer paygradesId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.position_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer positionId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.logicToDelete
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer logictodelete;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_emp.status
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.id
     *
     * @return the value of ehr_emp.id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.id
     *
     * @param id the value for ehr_emp.id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.userid
     *
     * @return the value of ehr_emp.userid
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.userid
     *
     * @param userid the value for ehr_emp.userid
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setUserid(String userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.sign
     *
     * @return the value of ehr_emp.sign
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getSign() {
        return sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.sign
     *
     * @param sign the value for ehr_emp.sign
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setSign(String sign) {
        this.sign = sign;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.avatar
     *
     * @return the value of ehr_emp.avatar
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.avatar
     *
     * @param avatar the value for ehr_emp.avatar
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.name
     *
     * @return the value of ehr_emp.name
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.name
     *
     * @param name the value for ehr_emp.name
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.password
     *
     * @return the value of ehr_emp.password
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.password
     *
     * @param password the value for ehr_emp.password
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.img
     *
     * @return the value of ehr_emp.img
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getImg() {
        return img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.img
     *
     * @param img the value for ehr_emp.img
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setImg(String img) {
        this.img = img;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.birthday
     *
     * @return the value of ehr_emp.birthday
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.birthday
     *
     * @param birthday the value for ehr_emp.birthday
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.sex
     *
     * @return the value of ehr_emp.sex
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.sex
     *
     * @param sex the value for ehr_emp.sex
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setSex(String sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.phone
     *
     * @return the value of ehr_emp.phone
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.phone
     *
     * @param phone the value for ehr_emp.phone
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.QQ
     *
     * @return the value of ehr_emp.QQ
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.QQ
     *
     * @param qq the value for ehr_emp.QQ
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setQq(String qq) {
        this.qq = qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.email
     *
     * @return the value of ehr_emp.email
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.email
     *
     * @param email the value for ehr_emp.email
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.age
     *
     * @return the value of ehr_emp.age
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.age
     *
     * @param age the value for ehr_emp.age
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.currentAddress
     *
     * @return the value of ehr_emp.currentAddress
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getCurrentaddress() {
        return currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.currentAddress
     *
     * @param currentaddress the value for ehr_emp.currentAddress
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setCurrentaddress(String currentaddress) {
        this.currentaddress = currentaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.inductionTime
     *
     * @return the value of ehr_emp.inductionTime
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Date getInductiontime() {
        return inductiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.inductionTime
     *
     * @param inductiontime the value for ehr_emp.inductionTime
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setInductiontime(Date inductiontime) {
        this.inductiontime = inductiontime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.state
     *
     * @return the value of ehr_emp.state
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.state
     *
     * @param state the value for ehr_emp.state
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.specialty
     *
     * @return the value of ehr_emp.specialty
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getSpecialty() {
        return specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.specialty
     *
     * @param specialty the value for ehr_emp.specialty
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setSpecialty(String specialty) {
        this.specialty = specialty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.mark
     *
     * @return the value of ehr_emp.mark
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.mark
     *
     * @param mark the value for ehr_emp.mark
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.isLogin
     *
     * @return the value of ehr_emp.isLogin
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getIslogin() {
        return islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.isLogin
     *
     * @param islogin the value for ehr_emp.isLogin
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setIslogin(Integer islogin) {
        this.islogin = islogin;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.dept_id
     *
     * @return the value of ehr_emp.dept_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.dept_id
     *
     * @param deptId the value for ehr_emp.dept_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.paygrades_id
     *
     * @return the value of ehr_emp.paygrades_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getPaygradesId() {
        return paygradesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.paygrades_id
     *
     * @param paygradesId the value for ehr_emp.paygrades_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setPaygradesId(Integer paygradesId) {
        this.paygradesId = paygradesId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.position_id
     *
     * @return the value of ehr_emp.position_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getPositionId() {
        return positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.position_id
     *
     * @param positionId the value for ehr_emp.position_id
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setPositionId(Integer positionId) {
        this.positionId = positionId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.logicToDelete
     *
     * @return the value of ehr_emp.logicToDelete
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.logicToDelete
     *
     * @param logictodelete the value for ehr_emp.logicToDelete
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_emp.status
     *
     * @return the value of ehr_emp.status
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_emp.status
     *
     * @param status the value for ehr_emp.status
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}