package com.ehr.model;

public class EmpSalary {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
	private String empName;
	private String purchaseRate;
    private Integer id;

    @Override
	public String toString() {
		return "EmpSalary [empName=" + empName + ", purchaseRate=" + purchaseRate + ", id=" + id + ", basicsalary="
				+ basicsalary + ", subsidies=" + subsidies + ", socialsecurityId=" + socialsecurityId + ", empId="
				+ empId + ", logictodelete=" + logictodelete + "]";
	}

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.basicSalary
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    private Integer basicsalary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.subsidies
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    private Integer subsidies;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.socialSecurity_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    private Integer socialsecurityId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.emp_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_compensation.logicToDelete
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.id
     *
     * @return the value of ehr_compensation.id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.id
     *
     * @param id the value for ehr_compensation.id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.basicSalary
     *
     * @return the value of ehr_compensation.basicSalary
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getBasicsalary() {
        return basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.basicSalary
     *
     * @param basicsalary the value for ehr_compensation.basicSalary
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setBasicsalary(Integer basicsalary) {
        this.basicsalary = basicsalary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.subsidies
     *
     * @return the value of ehr_compensation.subsidies
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getSubsidies() {
        return subsidies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.subsidies
     *
     * @param subsidies the value for ehr_compensation.subsidies
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setSubsidies(Integer subsidies) {
        this.subsidies = subsidies;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.socialSecurity_id
     *
     * @return the value of ehr_compensation.socialSecurity_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getSocialsecurityId() {
        return socialsecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.socialSecurity_id
     *
     * @param socialsecurityId the value for ehr_compensation.socialSecurity_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setSocialsecurityId(Integer socialsecurityId) {
        this.socialsecurityId = socialsecurityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.emp_id
     *
     * @return the value of ehr_compensation.emp_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.emp_id
     *
     * @param empId the value for ehr_compensation.emp_id
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_compensation.logicToDelete
     *
     * @return the value of ehr_compensation.logicToDelete
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_compensation.logicToDelete
     *
     * @param logictodelete the value for ehr_compensation.logicToDelete
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

	public String getPurchaseRate() {
		return purchaseRate;
	}

	public void setPurchaseRate(String purchaseRate) {
		this.purchaseRate = purchaseRate;
	}

	public String getEmpName() {
		return empName;
	}

	public void setEmpName(String empName) {
		this.empName = empName;
	}
}