package com.ehr.model;

import java.util.Date;

public class Expend {
    @Override
    public String toString() {
        return "Expend{" +
                "id=" + id +
                ", dept='" + dept + '\'' +
                ", money=" + money +
                ", date=" + date +
                ", companyId='" + companyId + '\'' +
                '}';
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbi_expend.id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbi_expend.dept
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    private String dept;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbi_expend.money
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    private Double money;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbi_expend.date
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    private Date date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dbi_expend.company_id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_expend.id
     *
     * @return the value of dbi_expend.id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_expend.id
     *
     * @param id the value for dbi_expend.id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_expend.dept
     *
     * @return the value of dbi_expend.dept
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_expend.dept
     *
     * @param dept the value for dbi_expend.dept
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_expend.money
     *
     * @return the value of dbi_expend.money
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_expend.money
     *
     * @param money the value for dbi_expend.money
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_expend.date
     *
     * @return the value of dbi_expend.date
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_expend.date
     *
     * @param date the value for dbi_expend.date
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_expend.company_id
     *
     * @return the value of dbi_expend.company_id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_expend.company_id
     *
     * @param companyId the value for dbi_expend.company_id
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }
}