package com.ehr.model;

import java.util.Date;
/**
 * 客户项目统计
 * @author WW
 *
 */
public class Income {
    private Integer id;//编号  主键
    private Integer fiveFifteen;//大于5万小于等于15万的项目
    private Integer fifteenThirty;//大于15万小于等于30万的项目
    private Integer thirtyFifty;//大于30万小于等于50万的项目
    private Integer fiftyHundred;//大于50万小于等于100万的项目
    private Integer hundredTwo;//大于100万小于等于200万的项目
    private Integer twoFive;//大于200万小于等于500万的项目
    private Integer fiveAbove;//大于500万的项目
    private Date date;//保存时间

    @Override
	public String toString() {
		return "Income [id=" + id + ", fiveFifteen=" + fiveFifteen + ", fifteenThirty=" + fifteenThirty
				+ ", thirtyFifty=" + thirtyFifty + ", fiftyHundred=" + fiftyHundred + ", hundredTwo=" + hundredTwo
				+ ", twoFive=" + twoFive + ", fiveAbove=" + fiveAbove + ", date=" + date + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.id
     *
     * @return the value of dbi_income.id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.id
     *
     * @param id the value for dbi_income.id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.five_fifteen
     *
     * @return the value of dbi_income.five_fifteen
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getFiveFifteen() {
        return fiveFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.five_fifteen
     *
     * @param fiveFifteen the value for dbi_income.five_fifteen
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setFiveFifteen(Integer fiveFifteen) {
        this.fiveFifteen = fiveFifteen;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.fifteen_thirty
     *
     * @return the value of dbi_income.fifteen_thirty
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getFifteenThirty() {
        return fifteenThirty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.fifteen_thirty
     *
     * @param fifteenThirty the value for dbi_income.fifteen_thirty
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setFifteenThirty(Integer fifteenThirty) {
        this.fifteenThirty = fifteenThirty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.thirty_fifty
     *
     * @return the value of dbi_income.thirty_fifty
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getThirtyFifty() {
        return thirtyFifty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.thirty_fifty
     *
     * @param thirtyFifty the value for dbi_income.thirty_fifty
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setThirtyFifty(Integer thirtyFifty) {
        this.thirtyFifty = thirtyFifty;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.fifty_hundred
     *
     * @return the value of dbi_income.fifty_hundred
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getFiftyHundred() {
        return fiftyHundred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.fifty_hundred
     *
     * @param fiftyHundred the value for dbi_income.fifty_hundred
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setFiftyHundred(Integer fiftyHundred) {
        this.fiftyHundred = fiftyHundred;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.hundred_two
     *
     * @return the value of dbi_income.hundred_two
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getHundredTwo() {
        return hundredTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.hundred_two
     *
     * @param hundredTwo the value for dbi_income.hundred_two
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setHundredTwo(Integer hundredTwo) {
        this.hundredTwo = hundredTwo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.two_five
     *
     * @return the value of dbi_income.two_five
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getTwoFive() {
        return twoFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.two_five
     *
     * @param twoFive the value for dbi_income.two_five
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setTwoFive(Integer twoFive) {
        this.twoFive = twoFive;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.Five_above
     *
     * @return the value of dbi_income.Five_above
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getFiveAbove() {
        return fiveAbove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.Five_above
     *
     * @param fiveAbove the value for dbi_income.Five_above
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setFiveAbove(Integer fiveAbove) {
        this.fiveAbove = fiveAbove;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_income.date
     *
     * @return the value of dbi_income.date
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_income.date
     *
     * @param date the value for dbi_income.date
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }
}