package com.ehr.model;

import com.fasterxml.jackson.annotation.JsonFormat;

import java.util.Date;

/**
 * 人力资源 人数统计
 * @author WW
 *
 */
public class Number {
    private Integer id;//主键 编号
    private String dept;//部门
    private Integer people;//人数
    @JsonFormat(pattern="yyyy-MM-dd")
    private Date date;//查询日期
    private Integer companyId;//对应公司的Id

	@Override
	public String toString() {
		return "Number [id=" + id + ", dept=" + dept + ", people=" + people + ", date=" + date + ", companyId="
				+ companyId + "]";
	}

	/**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_number.id
     *
     * @return the value of dbi_number.id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_number.id
     *
     * @param id the value for dbi_number.id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_number.dept
     *
     * @return the value of dbi_number.dept
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public String getDept() {
        return dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_number.dept
     *
     * @param dept the value for dbi_number.dept
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setDept(String dept) {
        this.dept = dept;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_number.people
     *
     * @return the value of dbi_number.people
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getPeople() {
        return people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_number.people
     *
     * @param people the value for dbi_number.people
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setPeople(Integer people) {
        this.people = people;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_number.date
     *
     * @return the value of dbi_number.date
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Date getDate() {
        return date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_number.date
     *
     * @param date the value for dbi_number.date
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setDate(Date date) {
        this.date = date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dbi_number.company_id
     *
     * @return the value of dbi_number.company_id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public Integer getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dbi_number.company_id
     *
     * @param companyId the value for dbi_number.company_id
     *
     * @mbg.generated Thu Jun 27 21:44:57 CST 2019
     */
    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }
}