package com.ehr.model;

public class Position {
    public Position() {
    }

    public Position(String name, String mark, Integer deptId, Integer logictodelete) {
        this.name = name;
        this.mark = mark;
        this.deptId = deptId;
        this.logictodelete = logictodelete;
    }

    public Position(Integer id, String name, String mark, Integer deptId, Integer logictodelete) {
        this.id = id;
        this.name = name;
        this.mark = mark;
        this.deptId = deptId;
        this.logictodelete = logictodelete;
    }

    private String deptName;

    @Override
    public String toString() {
        return "Position{" +
                "deptName='" + deptName + '\'' +
                ", id=" + id +
                ", name='" + name + '\'' +
                ", mark='" + mark + '\'' +
                ", deptId=" + deptId +
                ", logictodelete=" + logictodelete +
                '}';
    }

    public String getDeptName() {
        return deptName;
    }

    public void setDeptName(String deptName) {
        this.deptName = deptName;
    }

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_position.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_position.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_position.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_position.dept_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer deptId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_position.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_position.id
     *
     * @return the value of ehr_position.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_position.id
     *
     * @param id the value for ehr_position.id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_position.name
     *
     * @return the value of ehr_position.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_position.name
     *
     * @param name the value for ehr_position.name
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_position.mark
     *
     * @return the value of ehr_position.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_position.mark
     *
     * @param mark the value for ehr_position.mark
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_position.dept_id
     *
     * @return the value of ehr_position.dept_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getDeptId() {
        return deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_position.dept_id
     *
     * @param deptId the value for ehr_position.dept_id
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setDeptId(Integer deptId) {
        this.deptId = deptId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_position.logicToDelete
     *
     * @return the value of ehr_position.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_position.logicToDelete
     *
     * @param logictodelete the value for ehr_position.logicToDelete
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}