package com.ehr.model;

public class Rule {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.rulesName
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String rulesname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.clockInNum
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer clockinnum;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.amStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String amstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.amEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String amendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.pmStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String pmstarttime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.pmEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String pmendtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.clockInIocation
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private String clockiniocation;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.instructions
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer instructions;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_rule.logictoDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.id
     *
     * @return the value of ehr_rule.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.id
     *
     * @param id the value for ehr_rule.id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.rulesName
     *
     * @return the value of ehr_rule.rulesName
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getRulesname() {
        return rulesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.rulesName
     *
     * @param rulesname the value for ehr_rule.rulesName
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setRulesname(String rulesname) {
        this.rulesname = rulesname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.clockInNum
     *
     * @return the value of ehr_rule.clockInNum
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getClockinnum() {
        return clockinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.clockInNum
     *
     * @param clockinnum the value for ehr_rule.clockInNum
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setClockinnum(Integer clockinnum) {
        this.clockinnum = clockinnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.amStartTime
     *
     * @return the value of ehr_rule.amStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getAmstarttime() {
        return amstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.amStartTime
     *
     * @param amstarttime the value for ehr_rule.amStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setAmstarttime(String amstarttime) {
        this.amstarttime = amstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.amEndTime
     *
     * @return the value of ehr_rule.amEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getAmendtime() {
        return amendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.amEndTime
     *
     * @param amendtime the value for ehr_rule.amEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setAmendtime(String amendtime) {
        this.amendtime = amendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.pmStartTime
     *
     * @return the value of ehr_rule.pmStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getPmstarttime() {
        return pmstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.pmStartTime
     *
     * @param pmstarttime the value for ehr_rule.pmStartTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setPmstarttime(String pmstarttime) {
        this.pmstarttime = pmstarttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.pmEndTime
     *
     * @return the value of ehr_rule.pmEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getPmendtime() {
        return pmendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.pmEndTime
     *
     * @param pmendtime the value for ehr_rule.pmEndTime
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setPmendtime(String pmendtime) {
        this.pmendtime = pmendtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.clockInIocation
     *
     * @return the value of ehr_rule.clockInIocation
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public String getClockiniocation() {
        return clockiniocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.clockInIocation
     *
     * @param clockiniocation the value for ehr_rule.clockInIocation
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setClockiniocation(String clockiniocation) {
        this.clockiniocation = clockiniocation;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.instructions
     *
     * @return the value of ehr_rule.instructions
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getInstructions() {
        return instructions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.instructions
     *
     * @param instructions the value for ehr_rule.instructions
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setInstructions(Integer instructions) {
        this.instructions = instructions;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.emp_id
     *
     * @return the value of ehr_rule.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.emp_id
     *
     * @param empId the value for ehr_rule.emp_id
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_rule.logictoDelete
     *
     * @return the value of ehr_rule.logictoDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_rule.logictoDelete
     *
     * @param logictodelete the value for ehr_rule.logictoDelete
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }

	public Rule(Integer id, String rulesname, Integer clockinnum, String amstarttime, String amendtime,
			String pmstarttime, String pmendtime, String clockiniocation, Integer instructions, Integer empId,
			Integer logictodelete) {
		super();
		this.id = id;
		this.rulesname = rulesname;
		this.clockinnum = clockinnum;
		this.amstarttime = amstarttime;
		this.amendtime = amendtime;
		this.pmstarttime = pmstarttime;
		this.pmendtime = pmendtime;
		this.clockiniocation = clockiniocation;
		this.instructions = instructions;
		this.empId = empId;
		this.logictodelete = logictodelete;
	}

	public Rule() {
		super();
		// TODO Auto-generated constructor stub
	}
    
}