package com.ehr.model;

public class SalaryLever {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_paygrades.id
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_paygrades.name
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_paygrades.salary
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    private Integer salary;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_paygrades.mark
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    private String mark;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_paygrades.logicToDelete
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_paygrades.id
     *
     * @return the value of ehr_paygrades.id
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_paygrades.id
     *
     * @param id the value for ehr_paygrades.id
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_paygrades.name
     *
     * @return the value of ehr_paygrades.name
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_paygrades.name
     *
     * @param name the value for ehr_paygrades.name
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_paygrades.salary
     *
     * @return the value of ehr_paygrades.salary
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public Integer getSalary() {
        return salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_paygrades.salary
     *
     * @param salary the value for ehr_paygrades.salary
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public void setSalary(Integer salary) {
        this.salary = salary;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_paygrades.mark
     *
     * @return the value of ehr_paygrades.mark
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public String getMark() {
        return mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_paygrades.mark
     *
     * @param mark the value for ehr_paygrades.mark
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public void setMark(String mark) {
        this.mark = mark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_paygrades.logicToDelete
     *
     * @return the value of ehr_paygrades.logicToDelete
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_paygrades.logicToDelete
     *
     * @param logictodelete the value for ehr_paygrades.logicToDelete
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}