package com.ehr.model;

import java.util.Date;

public class SalaryList {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.emp_id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer empId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.empName
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private String empname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.shouldSend
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer shouldsend;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.bonus
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer bonus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.fine
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer fine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.insured
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer insured;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.time
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Date time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.realHair
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer realhair;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_articlewages.logicToDelete
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.id
     *
     * @return the value of ehr_articlewages.id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.id
     *
     * @param id the value for ehr_articlewages.id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.emp_id
     *
     * @return the value of ehr_articlewages.emp_id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getEmpId() {
        return empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.emp_id
     *
     * @param empId the value for ehr_articlewages.emp_id
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setEmpId(Integer empId) {
        this.empId = empId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.empName
     *
     * @return the value of ehr_articlewages.empName
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public String getEmpname() {
        return empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.empName
     *
     * @param empname the value for ehr_articlewages.empName
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setEmpname(String empname) {
        this.empname = empname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.shouldSend
     *
     * @return the value of ehr_articlewages.shouldSend
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getShouldsend() {
        return shouldsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.shouldSend
     *
     * @param shouldsend the value for ehr_articlewages.shouldSend
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setShouldsend(Integer shouldsend) {
        this.shouldsend = shouldsend;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.bonus
     *
     * @return the value of ehr_articlewages.bonus
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getBonus() {
        return bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.bonus
     *
     * @param bonus the value for ehr_articlewages.bonus
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setBonus(Integer bonus) {
        this.bonus = bonus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.fine
     *
     * @return the value of ehr_articlewages.fine
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getFine() {
        return fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.fine
     *
     * @param fine the value for ehr_articlewages.fine
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setFine(Integer fine) {
        this.fine = fine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.insured
     *
     * @return the value of ehr_articlewages.insured
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getInsured() {
        return insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.insured
     *
     * @param insured the value for ehr_articlewages.insured
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setInsured(Integer insured) {
        this.insured = insured;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.time
     *
     * @return the value of ehr_articlewages.time
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Date getTime() {
        return time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.time
     *
     * @param time the value for ehr_articlewages.time
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setTime(Date time) {
        this.time = time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.realHair
     *
     * @return the value of ehr_articlewages.realHair
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getRealhair() {
        return realhair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.realHair
     *
     * @param realhair the value for ehr_articlewages.realHair
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setRealhair(Integer realhair) {
        this.realhair = realhair;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_articlewages.logicToDelete
     *
     * @return the value of ehr_articlewages.logicToDelete
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_articlewages.logicToDelete
     *
     * @param logictodelete the value for ehr_articlewages.logicToDelete
     *
     * @mbg.generated Fri Jun 28 21:04:19 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}