package com.ehr.model;

public class Social {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_socialsecurity.id
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_socialsecurity.purchaseRate
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    private Integer purchaserate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ehr_socialsecurity.logicToDelete
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    private Integer logictodelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_socialsecurity.id
     *
     * @return the value of ehr_socialsecurity.id
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_socialsecurity.id
     *
     * @param id the value for ehr_socialsecurity.id
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_socialsecurity.purchaseRate
     *
     * @return the value of ehr_socialsecurity.purchaseRate
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public Integer getPurchaserate() {
        return purchaserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_socialsecurity.purchaseRate
     *
     * @param purchaserate the value for ehr_socialsecurity.purchaseRate
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public void setPurchaserate(Integer purchaserate) {
        this.purchaserate = purchaserate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ehr_socialsecurity.logicToDelete
     *
     * @return the value of ehr_socialsecurity.logicToDelete
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public Integer getLogictodelete() {
        return logictodelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ehr_socialsecurity.logicToDelete
     *
     * @param logictodelete the value for ehr_socialsecurity.logicToDelete
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    public void setLogictodelete(Integer logictodelete) {
        this.logictodelete = logictodelete;
    }
}