package com.ehr.dao;

import com.ehr.model.Activity;
import com.ehr.model.pojo.ActivityQiantai;
import com.ehr.model.pojo.AttendanceQiantai;

import java.util.List;

import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ActivityDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_activity
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_activity
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    int insert(Activity record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_activity
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    Activity selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_activity
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    List<Activity> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_activity
     *
     * @mbg.generated Sun Jun 23 19:50:14 CST 2019
     */
    int updateByPrimaryKey(Activity record);
    
    
    @Select("SELECT ehr_activity.theme,ehr_activity.activityAddress,ehr_activity.introduce,ehr_activity.activityTheDetail,ehr_activity.initateTime,ehr_activity.spending,ehr_activity.state,ehr_emp.`name`,ehr_activity.id\r\n" + 
    		"FROM ehr_activity,ehr_emp\r\n" + 
    		"WHERE ehr_activity.emp_id = ehr_emp.id\r\n" + 
    		"")
    List<ActivityQiantai> selectAllqiantai();
    
    List<ActivityQiantai> selectLike(@Param("name") String name,@Param("activityAddress")String activityAddress);
}