package com.ehr.dao;

import com.ehr.model.Dept;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface DeptDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_dept
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_dept
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int insert(Dept record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_dept
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    Dept selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_dept
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    List<Dept> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_dept
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int updateByPrimaryKey(Dept record);


    List<Dept> likeSearch(@Param("deptName") String deptName ,@Param("companyId") Integer companyId);
}