package com.ehr.dao;

import com.ehr.model.EmpSalary;
import java.util.List;

public interface EmpSalaryDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_compensation
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_compensation
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    int insert(EmpSalary record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_compensation
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    EmpSalary selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_compensation
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    List<EmpSalary> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_compensation
     *
     * @mbg.generated Sat Jun 29 09:28:26 CST 2019
     */
    int updateByPrimaryKey(EmpSalary record);
}