package com.ehr.dao;

import com.ehr.model.Emp;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface EmpWjkDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    int insert(Emp record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    Emp selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    List<Emp> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_emp
     *
     * @mbg.generated Fri Jun 28 22:48:24 CST 2019
     */
    int updateByPrimaryKey(Emp record);

	List<Emp> selectLike(@Param("id") Integer id, @Param("sex") String sex);
}