package com.ehr.dao;

import com.ehr.model.Expend;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

import java.util.Date;
import java.util.List;

public interface ExpendDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbi_expend
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbi_expend
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    int insert(Expend record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbi_expend
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    Expend selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbi_expend
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    List<Expend> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dbi_expend
     *
     * @mbg.generated Thu Jun 27 19:47:59 CST 2019
     */
    int updateByPrimaryKey(Expend record);


    /**
     * 查询该表所有公司id 并返回名称，注意 不要重复
     * */
    List<String> checkReturnNameByCompanyId();
   /**
    * 查询表中所有日期，不重复
    * */
    List<Expend> checkReturnDates();
    /**
     * 根据date和name查所有相关记录
     * */
    List<Expend> checkByNameAndDate(@Param(value = "date")String date ,@Param(value = "name") String name);


}