package com.ehr.dao;

import com.ehr.model.Pos;

import java.util.List;

public interface PosDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Fri Jun 28 23:51:39 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Fri Jun 28 23:51:39 CST 2019
     */
    int insert(Pos record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Fri Jun 28 23:51:39 CST 2019
     */
    Pos selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Fri Jun 28 23:51:39 CST 2019
     */
    List<Pos> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Fri Jun 28 23:51:39 CST 2019
     */
    int updateByPrimaryKey(Pos record);
}