package com.ehr.dao;

import com.ehr.model.Dept;
import com.ehr.model.Position;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PositionDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int insert(Position record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    Position selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    List<Position> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_position
     *
     * @mbg.generated Tue Jun 25 14:56:12 CST 2019
     */
    int updateByPrimaryKey(Position record);

    List<Position> likeSearch(@Param("positionName") String positionName , @Param("deptId") Integer deptId);
}