package com.ehr.dao;

import com.ehr.model.SalaryLever;
import java.util.List;

public interface SalaryLeverDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_paygrades
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_paygrades
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    int insert(SalaryLever record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_paygrades
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    SalaryLever selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_paygrades
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    List<SalaryLever> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_paygrades
     *
     * @mbg.generated Fri Jun 28 10:57:26 CST 2019
     */
    int updateByPrimaryKey(SalaryLever record);
}