package com.ehr.dao;

import com.ehr.model.Social;
import java.util.List;

public interface SocialDao {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_socialsecurity
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_socialsecurity
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    int insert(Social record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_socialsecurity
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    Social selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_socialsecurity
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    List<Social> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ehr_socialsecurity
     *
     * @mbg.generated Thu Jun 27 11:20:47 CST 2019
     */
    int updateByPrimaryKey(Social record);
}