server: 
  port: 80
spring:
   mvc:
     view:
       prefix: /WEB-INF/View/ 
       suffix: .jsp
   datasource:
    driverClassName: com.mysql.jdbc.Driver
    url : jdbc:mysql://localhost:3306/ym-ehr-oa?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8 
    username : root
    password : admin
# Mybatis
mybatis:
  typeAliasesPackage: com.ehr.model   
  mapperLocations: classpath:com/ehr/dao/mapper/*.xml
---
spring: 
   mail:
     host: smtp.qq.com
     username: 1072571403@qq.com
     password: jgarkozzzrmlbfdg